# Generated by Django 3.2.13 on 2022-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=320)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=3000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
