# Generated by Django 3.2.13 on 2022-07-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220714_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='email',
        ),
    ]
