# Generated by Django 3.2.13 on 2022-06-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-updated_on']},
        ),
    ]
