# Generated by Django 3.2.13 on 2022-06-29 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
