# Generated by Django 3.2.13 on 2022-07-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_on',
        ),
    ]
