# Generated by Django 3.2.13 on 2022-06-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('Top', 1), ('High', 2), ('Normal', 3), ('Low', 4), ('Bottom', 5)], default='Normal', max_length=6),
        ),
    ]
