# Generated by Django 3.2.13 on 2022-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('1 - Top', 1), ('2 - High', 2), ('3 - Normal', 3), ('4 - Low', 4), ('5 - Bottom', 5)], default='Normal', max_length=10),
        ),
    ]
