# Generated by Django 3.2.13 on 2022-06-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('1 - Top', 'Top'), ('2 - High', 'High'), ('3 - Normal', 'Normal'), ('4 - Low', 'Low'), ('5 - Bottom', 'Bottom')], default='Normal', max_length=10),
        ),
    ]
