# Generated by Django 3.2.13 on 2022-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(blank=True, default='Please enquire at reception', max_length=150),
        ),
    ]
